### ISSUE TITLE
02-JVM监控及诊断工具-命令行篇.md 一些拼写问题

### ISSUE THREAD

**Issue by anaer** [shaoxiongdu/JVMStudy#1]
![image](https://user-images.githubusercontent.com/4637100/126423355-a1ba3424-7e2c-4e6e-8d94-25e16ca1679a.png)
![image](https://user-images.githubusercontent.com/4637100/126423884-6a6f7593-9cda-46a2-bd9c-81e39df621f4.png)
![image](https://user-images.githubusercontent.com/4637100/126423939-daefce59-fc51-4cfa-804d-b1853404a84c.png)
![image](https://user-images.githubusercontent.com/4637100/126424636-1cf60b49-0f04-4734-a13c-3a0a5d6c380e.png)

**Comment by shaoxiongdu** [comment]
感谢 ！

**Comment by shaoxiongdu** [comment]
感谢兄弟指出，从书中摘抄过来纯手打难免有错误，抱歉~
