### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by realLiuzh** [shaoxiongdu/JVMStudy#5]
坐标：02-运行时数据区/06-堆.md中动态对象年龄判断
该算法是指：对于幸存区中，如果年龄1~x的对象大小大于幸存区大小的一半，年龄≥x的对象晋升到老年代。
这样做的原因是为了避免晋升年龄过大，导致新生代的对象无法晋升。
参考：
https://www.cnblogs.com/zjfjava/p/13861797.html
https://segmentfault.com/a/1190000039805691

**Comment by shaoxiongdu** [comment]
已合入您的正确版本
